### ISSUE TITLE
go get cannot find package "github.com/putdotio/go-putio/putio"

### ISSUE THREAD

**Issue by robinv85** [daptin/daptin#81]
Just running go get resolved in this console message:

```
$ go get github.com/daptin/daptin
package github.com/putdotio/go-putio/putio: cannot find package "github.com/putdotio/go-putio/putio" in any of:
	/usr/local/Cellar/go/1.14/libexec/src/github.com/putdotio/go-putio/putio (from $GOROOT)
	/Users/robin/go/src/github.com/putdotio/go-putio/putio (from $GOPATH)
```

Might need to update dependencies?

**Comment by artpar** [comment]
Updated the dependency. Waiting for CI build. Build is working fine locally.

**Comment by artpar** [comment]
Can you try now, [travis build](https://travis-ci.org/daptin/daptin/builds/660246367?utm_medium=notification&utm_source=github_status) is successful

**Comment by robinv85** [comment]
Hmm ok, I've uninstalled the package completely with `go clean` and retried, still get the same error / warning message (not sure if this is an error or warning since it doesn't show that).

Similar error happens for `go install github.com/daptin/daptin` by the way

```
$ go install github.com/daptin/daptin
artpar/rclone/backend/putio/error.go:8:2: cannot find package "github.com/putdotio/go-putio/putio" in any of:
	/usr/local/Cellar/go/1.14/libexec/src/github.com/putdotio/go-putio/putio (from $GOROOT)
	/Users/robin/go/src/github.com/putdotio/go-putio/putio (from $GOPATH)
```

**Comment by artpar** [comment]
Can you tell your go version ?

**Comment by robinv85** [comment]
`go1.14 darwin/amd64` 

not sure if this is ok, I have `GO111MODULE=""` when I check `go env`

**Comment by artpar** [comment]
I think go modules are enabled by default in go 1.14. I am trying to build this in a fresh 1.14 go container hoping to reproduce this at my end.

**Comment by artpar** [comment]
I am able to reproduce this. 

```
> go get github.com/daptin/daptin

> go install github.com/daptin/daptin

artpar/rclone/backend/putio/error.go:8:2: cannot find package "github.com/putdotio/go-putio/putio" in any of:
	/usr/local/Cellar/go/1.14/libexec/src/github.com/putdotio/go-putio/putio (from $GOROOT)
	/Users/robin/go/src/github.com/putdotio/go-putio/putio (from $GOPATH)
```

I went to the source dir in `$GOROOT/github.com/daptin/daptin` and did a `go get` there, and this fetched the putio transitive dependency.

Need to fix why putio isn't being fetched in the first `go get` itself. Our `go.sum` does reflect the dependency on it.

Trying out a couple of things to solve this.

**Comment by robinv85** [comment]
@artpar Maybe just need to fix module path? seems like it was recently updated in the putio repo: https://github.com/putdotio/go-putio/commit/18e0523a59ac351a8f8cf749ba08c83dc9935849
https://github.com/putdotio/go-putio/commit/2cacd2485b0736f14d5915521202f7d4d57d38ea

**Comment by artpar** [comment]
So actually this issue is resolved, but I encountered another strange behavior on fresh go get .../daptin but the builds are all fine.

Can you try go get again ?

**Comment by robinv85** [comment]
Still having the same issue for `go get github.com/daptin/daptin` and now another one too

```
package github.com/putdotio/go-putio/putio: cannot find package "github.com/putdotio/go-putio/putio" in any of:
	/usr/local/Cellar/go/1.14/libexec/src/github.com/putdotio/go-putio/putio (from $GOROOT)
	/Users/robin/go/src/github.com/putdotio/go-putio/putio (from $GOPATH)
package github.com/tealeg/xlsx/v2: cannot find package "github.com/tealeg/xlsx/v2" in any of:
	/usr/local/Cellar/go/1.14/libexec/src/github.com/tealeg/xlsx/v2 (from $GOROOT)
	/Users/robin/go/src/github.com/tealeg/xlsx/v2 (from $GOPATH)
```

Also checked where `putio` is coming from with `go mod why github.com/putdotio/go-putio/putio` and it's sub dependency from `github.com/artpar/rclone`.

`go install` seems to work now without the warning message.

**Comment by artpar** [comment]
Is that on after clean or on existing go get instance ?

The artpar/rclone is my fork of rclone/rclone which replaces panic's with error reports (because we dont want server to die because of a file io error) 

I am seeing only the second one (tealeg/xlsx) and I am currently working on that.
```
root@6521a6b61796:/go# go install github.com/daptin/daptin
src/github.com/daptin/daptin/server/resource/action_xls_to_entity.go:11:2: cannot find package "github.com/tealeg/xlsx/v2" in any of:
	/usr/local/go/src/github.com/tealeg/xlsx/v2 (from $GOROOT)
	/go/src/github.com/tealeg/xlsx/v2 (from $GOPATH)

```
```
root@6521a6b61796:/go# go get github.com/tealeg/xlsx/v2
package github.com/tealeg/xlsx/v2: cannot find package "github.com/tealeg/xlsx/v2" in any of:
	/usr/local/go/src/github.com/tealeg/xlsx/v2 (from $GOROOT)
	/go/src/github.com/tealeg/xlsx/v2 (from $GOPATH)
```

I think this is because of the missing branch named v2 in that repo, I will have to fork that too probably.

**Comment by robinv85** [comment]
Yeah I did clean, now I also only get the second one for `github.com/tealeg/xlsx/v2`
 Thanks for checking, @artpar  I'll close this issue. 

Was just a bit confusing because the docs mentioned just run `go get` to get started, would be nice if this project is stable to check it out.

**Comment by artpar** [comment]
Yeah I never realized the a fresh go get was having this issue. Thanks for bringing it to attention. The fix for the xlsx/v2 is on the way :)

**Comment by artpar** [comment]
Try now, should work perfectly well on a new go get. Resolved both the issues.

**Comment by robinv85** [comment]
Seems fixed now, but I see another message:
```
$ go get github.com/daptin/daptin
# github.com/daptin/daptin/server/resource
daptin/daptin/server/resource/action_xls_to_entity.go:334:12: assignment mismatch: 1 variable but sheet.Row returns 2 values
daptin/daptin/server/resource/action_xls_to_entity.go:351:14: assignment mismatch: 1 variable but sheet.Row returns 2 values

```

**Comment by robinv85** [comment]
Ok, I had it a few times, then did a `go clean` and manually removed the package and now it seems to work for both `go get` and `go install` without any log message :)
